# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the lane"
  lane :build do
     build_app(scheme: "Build_test", skip_archive: true, skip_codesigning: true)
  end
end

platform :ios do
  desc "Run the tests"
  lane :test do
     run_tests(scheme: "Build_testTests",
                devices: ["iPhone 11"]
                )
  end
end

platform :ios do
  desc "testflight minor"
  lane :beta_new_minor do
     increment_buid_number
  end
end

platform :ios do
  desc "testflight patch"
  lane :beta_new_patch do
     increment_build_number
  end
end

platform :ios do
  desc "increment_ver"
  lane :bumpMinor do
    increment_version_number_in_xcodeproj(bump_type: "minor")
  end
end
