name: Build project

on:
  pull_request_target:
    types:
      - closed
    branches: [ main ]

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    permissions:
      issues: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.8"

    - name: Install fastlane
      run: brew install fastlane

    - name: Build
      run: |
        fastlane build
        
    - name: Add comment
      uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
      with:
        issue-number: 10
        body: |
         ${{ github.head_ref }}  
        

  create_minor_tag:
    name: Create minor tag
    needs: build
    if: ${{ github.head_ref == 'release/**' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@v1.1
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with: 
          github_token: ${{ secrets.TOKEN }}
          default_bump: minor
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  create_patch_tag:
    name: Create patch tag
    needs: build
    if: ${{ github.head_ref == 'hotfix/**' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@v1.1
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with: 
          github_token: ${{ secrets.TOKEN }}
          default_bump: patch
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
