# This is a basic workflow to help you get started with Actions

name: bump version

# Controls when the workflow will run
on:
  pull_request_target:
    types: 
      - closed
    branches: [ main ]

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.8"

      - name: Install fastlane
        run: brew install fastlane

      - name: bump version
        run: |
          fastlane bumpMinor
            
  openPR:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ secrets.TOKEN }}
          committer: Github <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: post_release
          base: develop
          body: |
            bump version in xcodeproj based on update type.
            from github actions cloud.
          
          
        
