# This is a basic workflow to help you get started with Actions

name: Comment on pr

on:
  pull_request

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
       - name: Comment PR
         uses: thollander/actions-comment-pull-request@v1
         with:
           message: 'LGTM!'
           pr_number: ${{github.event.number}} # This will comment on pull request #123
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
