# This is a basic workflow to help you get started with Actions

name: Comment on pr

on:
  pull_request

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
       - name: Comment
         uses: peter-evans/create-or-update-comment@v1
         with:
           issue-number: ${{github.event.pull_request.number}}
           body: "LGTM !"
