# This is a basic workflow to help you get started with Actions

name: Comment on pr

on:
  pull_request_target

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
       - name: Create comment
         uses: peter-evans/create-or-update-comment@v2
         with:
              issue-number: ${{github.event.number}}
              token: ENV["TOKEN"]
              body: |
                LGTM
