name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  builds:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
      
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.8"

    - name: Install fastlane
      run: brew install fastlane
      
    - name: Test on iPhone 11pro
      run: |
        fastlane test
