name: Test SSH installing on push

on:
    push:
        branches: [ develop ]

jobs:
    installSSH:
        name: InstallSSH
        
        runs-on: macos-12
        
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Select Xcode Version
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '13.4.0'
            
        - name: Install testkit SSH
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_TESTKIT }}
            known_hosts: unnecessary
        
        - name: Install Keychain ssh
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_KEYCHAINKIT }}
            known_hosts: unnecessary
            
        - name: print created files for ssh
          run: ls -l ~/.ssh
            
        - name: git clone with ssh testkit
          run: git clone git@github.com:eazel/iOSTestKit.git
          
        - name: git clone with ssh keychainkit
          run: git clone git@github.com:eazel/iOSKeychainServiceKit.git
          
        - name: print created files
          run: ls -l
